name: Build daily storefront

on:
  schedule:
    - cron: "0 12 * * *"   # 7am ET daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # needed for rebase/push

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Build storefront
        env:
          AMZ_ACCESS_KEY: ${{ secrets.AMZ_ACCESS_KEY }}
          AMZ_SECRET_KEY: ${{ secrets.AMZ_SECRET_KEY }}
          AMZ_PARTNER_TAG: ${{ secrets.AMZ_PARTNER_TAG }}
        run: python build_storefront.py

      - name: Commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git checkout main
          git pull --rebase origin main || true

          # stage everything in docs (tracked + untracked)
          git add -A docs

          if ! git diff --cached --quiet; then
            git commit -m "Daily storefront update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          else
            echo "no changes"
          fi
